# Generated by Django 4.2.4 on 2023-08-16 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='icone',
            field=models.CharField(choices=[('lni-users', 'Usuários'), ('lni-layers', 'Design'), ('lni-cog', 'Engrenagem'), ('lni-Stats-up', 'Gráfico'), ('lni-rocket', 'Foguete'), ('lni-mobile', 'Mobile')], max_length=12, verbose_name='Icone'),
        ),
    ]
