# Generated by Django 4.2.4 on 2023-08-17 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_servico_icone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='icone',
            field=models.CharField(choices=[('lni-rocket', 'Foguete'), ('lni-cog', 'Engrenagem'), ('lni-users', 'Usuários'), ('lni-mobile', 'Mobile'), ('lni-layers', 'Design'), ('lni-Stats-up', 'Gráfico')], max_length=12, verbose_name='Icone'),
        ),
    ]
