# Generated by Django 4.2.4 on 2023-08-17 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_servico_icone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='funcionario',
            options={'verbose_name': 'Funcionário', 'verbose_name_plural': 'Funcionarios'},
        ),
        migrations.AlterField(
            model_name='servico',
            name='icone',
            field=models.CharField(choices=[('lni-cog', 'Engrenagem'), ('lni-mobile', 'Mobile'), ('lni-layers', 'Design'), ('lni-users', 'Usuários'), ('lni-rocket', 'Foguete'), ('lni-Stats-up', 'Gráfico')], max_length=12, verbose_name='Icone'),
        ),
    ]
