# Generated by Django 4.2.4 on 2023-08-17 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_funcionario_options_alter_servico_icone'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='facebook',
            field=models.CharField(default='#', max_length=100, verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='instagram',
            field=models.CharField(default='#', max_length=100, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='twitter',
            field=models.CharField(default='#', max_length=100, verbose_name='Twitter'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='icone',
            field=models.CharField(choices=[('lni-layers', 'Design'), ('lni-cog', 'Engrenagem'), ('lni-mobile', 'Mobile'), ('lni-rocket', 'Foguete'), ('lni-users', 'Usuários'), ('lni-Stats-up', 'Gráfico')], max_length=12, verbose_name='Icone'),
        ),
    ]
