# Generated by Django 4.2.4 on 2023-08-17 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_servico_icone'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='bio',
            field=models.TextField(default='', max_length=200, verbose_name='Bio'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='icone',
            field=models.CharField(choices=[('lni-layers', 'Design'), ('lni-stats-up', 'Gráfico'), ('lni-rocket', 'Foguete'), ('lni-users', 'Usuários'), ('lni-cog', 'Engrenagem'), ('lni-mobile', 'Mobile')], max_length=12, verbose_name='Icone'),
        ),
    ]
