# Generated by Django 4.2.4 on 2023-08-17 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_funcionario_bio_alter_servico_icone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criados', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('descricao', models.TextField(default='', max_length=200, verbose_name='Descricao')),
                ('icone', models.CharField(choices=[('lni-layers', 'Layers'), ('lni-rocket', 'Foguete'), ('lni-laptop-phone', 'Fone'), ('lni-leaf', 'Folha'), ('lni-mobile', 'Mobile'), ('lni-cog', 'Engrenagem')], max_length=16, verbose_name='Icone')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='servico',
            name='icone',
            field=models.CharField(choices=[('lni-rocket', 'Foguete'), ('lni-users', 'Usuários'), ('lni-layers', 'Design'), ('lni-mobile', 'Mobile'), ('lni-stats-up', 'Gráfico'), ('lni-cog', 'Engrenagem')], max_length=12, verbose_name='Icone'),
        ),
    ]
