# Generated by Django 4.2.4 on 2023-08-17 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_features_icone_alter_servico_icone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='features',
            options={'verbose_name': 'porra', 'verbose_name_plural': 'caralhos'},
        ),
        migrations.AlterField(
            model_name='features',
            name='icone',
            field=models.CharField(choices=[('lni-rocket', 'Foguete'), ('lni-cog', 'Engrenagem'), ('lni-laptop-phone', 'Fone'), ('lni-leaf', 'Folha'), ('lni-mobile', 'Mobile'), ('lni-layers', 'Layers')], max_length=16, verbose_name='Icone'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='icone',
            field=models.CharField(choices=[('lni-stats-up', 'Gráfico'), ('lni-cog', 'Engrenagem'), ('lni-mobile', 'Mobile'), ('lni-users', 'Usuários'), ('lni-layers', 'Design'), ('lni-rocket', 'Foguete')], max_length=12, verbose_name='Icone'),
        ),
    ]
