# Generated by Django 4.2.4 on 2023-08-17 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_features_options_alter_features_icone_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='features',
            options={'verbose_name': 'Feature', 'verbose_name_plural': 'Features'},
        ),
        migrations.AlterField(
            model_name='features',
            name='icone',
            field=models.CharField(choices=[('lni-layers', 'Layers'), ('lni-rocket', 'Foguete'), ('lni-leaf', 'Folha'), ('lni-laptop-phone', 'Fone'), ('lni-mobile', 'Mobile'), ('lni-cog', 'Engrenagem')], max_length=16, verbose_name='Icone'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='icone',
            field=models.CharField(choices=[('lni-mobile', 'Mobile'), ('lni-layers', 'Design'), ('lni-rocket', 'Foguete'), ('lni-users', 'Usuários'), ('lni-stats-up', 'Gráfico'), ('lni-cog', 'Engrenagem')], max_length=12, verbose_name='Icone'),
        ),
    ]
