# Generated by Django 4.2.4 on 2023-08-17 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_features_options_alter_features_icone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='features',
            name='icone',
            field=models.CharField(choices=[('lni-laptop-phone', 'Fone'), ('lni-leaf', 'Folha'), ('lni-mobile', 'Mobile'), ('lni-rocket', 'Foguete'), ('lni-cog', 'Engrenagem'), ('lni-layers', 'Layers')], max_length=16, verbose_name='Icone'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='icone',
            field=models.CharField(choices=[('lni-mobile', 'Mobile'), ('lni-layers', 'Design'), ('lni-stats-up', 'Gráfico'), ('lni-rocket', 'Foguete'), ('lni-users', 'Usuários'), ('lni-cog', 'Engrenagem')], max_length=12, verbose_name='Icone'),
        ),
    ]
